apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: g4h5gj8vk-go 
  janus-idp.io/tekton: g4h5gj8vk-go
  backstage.io/kubernetes-id: g4h5gj8vk-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: g4h5gj8vk-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml